### ISSUE TITLE
Add data to end callback

### ISSUE THREAD

**Issue by erf** [rvagg/through2#49]
Is there a reason you don't allow writing data to the flush callback, like with the transform callback?

**Comment by rvagg** [comment]
you'll have to question this upstream @ https://github.com/nodejs/readable-stream as we're only implementing the streams2/3 mechanism

if you did add data on the flush callback, would that mean that you'd need another flush callback because it only gets flushed after that last chunk of data gets pushed through? where does this end?

**Comment by dwelle** [comment]
Just in case someone reads this, the aforementioned behavior is already implemented in latest `readable-stream`. Make sure you bump to latest though2 (`2.0.3`).

https://github.com/nodejs/readable-stream/issues/271
