### ISSUE TITLE
through2 does not support readableObjectMode and writableObjectMode

### ISSUE THREAD

**Issue by aptogo** [rvagg/through2#55]
through2 has a dependency on:
"name": "readable-stream",
  "version": "2.0.2",
  "description": "Streams3, a user-land copy of the stream library from iojs v2.x"

This does not support the split-mode options readableObjectMode and writableObjectMode that are now available on native streams in node 0.12.7. This makes it impossible to create a transformer that reads objects and writes buffers.

**Comment by rvagg** [comment]
@chrisdickinson do we have a discrepancy between features available streams in 3.x and 0.12? This is the first I've heard of these split objectMode options.

**Comment by juliangruber** [comment]
- node:
  - `master` has it: https://github.com/nodejs/node/blob/master/lib/_stream_readable.js#L23
  - `3.0` has it: https://github.com/nodejs/node/blob/v3.0.0/lib/_stream_readable.js#L23
  - `0.12` seems to have it: https://github.com/nodejs/node/blob/v0.12/lib/_stream_readable.js#L42 (i couldn't find a 0.12 tag, only the branch)
- readable-stream:
  - `master` has it: https://github.com/nodejs/readable-stream/blob/master/lib/_stream_readable.js#L73
  - `2.0.2` has it: https://github.com/nodejs/readable-stream/blob/v2.0.2/lib/_stream_readable.js#L73

So I'm guessing @aptogo the bug is somewhere else.

**Comment by aptogo** [comment]
Sorry, my mistake. I get readableObjectMode and writableObjectMode back to front. writableObjectMode sets the mode coming into the transform and readableObjectMode sets the mode going out of the transform.

**Comment by juliangruber** [comment]
yeah those terms can be confusing
