### ISSUE TITLE
return value of this.push()

### ISSUE THREAD

**Issue by krishnasrinivas** [rvagg/through2#63]
Is it safe to ignore the return value of this.push() in the transform function?

**Comment by brycebaril** [comment]
The return value of `this.push` is more-or-less advisory. Here's what it's telling you:
```js
  return !state.ended &&
         (state.needReadable ||
          state.length < state.highWaterMark ||
          state.length === 0);
```

So the possible reasons it would be `false` are:
* the stream has ended (shouldn't happen, instead you should get an error 'Error: stream.push() after EOF'

or
* the stream is buffering past the highWaterMark

Generally this is trying to allow you to control backpressure in your stream. Depending on what you are doing that could have very different realities when it comes to how to handle it.

Here are some examples:
* Your upstream data supplier is under full control and can be paused
Imagine your upstream is reading from the file system, a chunk of a file at a time. When the stream pipeline signals backpressure via `this.push` returning `false`, the upstream supplier can pause to avoid caching more data in memory before the stream is ready.

* Your upstream data supplier may not have a way to be paused, so you must buffer anyway.
In this case, paying attention to the return value isn't useful because you can't do anything with it anyway.

* Your upstream data supplier has temporally significant data
Imagine your upstream is a drone telemetry stream and you can't process the data as fast as it produces it. You need to listen to the return value of `this.push` and discard incoming upstream events until the stream has caught up again.


In terms of safety, the stream will continue to buffer more chunks even if the reply to `this.push` is false. In many (most?) cases, I would consider it safe to ignore. However, **depending on how much you're buffering, you could run into resource limits in extreme cases.** The specific details of your situation determine whether you should or even have the option of processing the signal.

**Comment by krishnasrinivas** [comment]
@brycebaril thanks for the detailed answer, that clears up everything.
