### ISSUE TITLE
Async issue

### ISSUE THREAD

**Issue by elsehow** [rvagg/through2#79]
Hi all,

I'm replicating together [two hyperlogs](https://github.com/mafintosh/hyperlog), and I find that this works:

```javascript
aliceReplication
pipe(through(function (buf, enc, next) {
   next(null, buf)
 }))
 .pipe(bobReplication)
 .pipe(aliceReplication)
```

but, this does not

```javascript
aliceReplication
pipe(through(function (buf, enc, next) {
   setTimeout(() => next(null, buf), 1)
 }))
 .pipe(bobReplication)
 .pipe(aliceReplication)
```

I find this behavior with all asynchronous functions. Any idea why this might be happening? I am having trouble finding similar issues.

(The stuff in my through stream needs to call back asynchronously - `setTimeout` serves as a minimal example).

**Comment by YounGoat** [comment]
I was blocked by the similar issue. The stream created by through2 is strictly restricted to something like REPL. Until the ``next()`` called, the following chunk will not be read and processed. 

I wrote [oct](https://www.npmjs.com/package/oct) to resolve this issue. However, only object mode is supported now.

**Comment by nevercast** [comment]
I see this was closed, but your solution was to use another package. Can this be reopened so that someone may provide details of how to implement this with through2. I had assumed that the callback would wait forever so that async calls would work. But in my case, the `end` event is being emitted, even if I don't call callback/next.
