### ISSUE TITLE
'end' emitted after 'finish'

### ISSUE THREAD

**Issue by noffle** [rvagg/through2#91]
```js
var through2 = require('through2')

var stream = through2(function write (data, enc, cb) {
  cb(null, data)
}, function flush (cb) {
  console.log('flush')
  setTimeout(function () {
    console.log('still flushing')
    cb()
  }, 100)
})

stream.on('finish', function () {
  console.log('finish event')
})

stream.end('hello')
```

outputs

```
flush
finish event
still flushing
```

See also https://github.com/rvagg/through2/issues/60

**Comment by mafintosh** [comment]
That's expected behavior. The writable side closes before the readable one.

**Comment by noffle** [comment]
@mafintosh The node docs [for 'finish'](https://nodejs.org/api/stream.html#stream_event_finish) say "The 'finish' event is emitted after the stream.end() method has been called, and all data has been flushed to the underlying system". However, here we see 'finish' being emitted *before* the flushing completes.

**Comment by mafintosh** [comment]
@noffle it's referring to flushing of the writable side. the _flush method of transforms work on the readable side

**Comment by noffle** [comment]
@mafintosh Thanks for helping me try and grok this.

>  it's referring to flushing of the writable side

I'm not sure I understand. Assumption: events for the readable and writable side are emitted with the same event emitter in a through stream. If this is so, how is `finish` coming up before `end`?

**Comment by gmaclennan** [comment]
@noffle As I understand it, transform streams are a little non-obvious with these `finish` and `end` events because they are both writable and readable.

The writeable is on the "input" side of the stream, so once that is finished, you will get the `finish` event. The readable side of the transport stream (the "output") will emit an `end` event when it has finished flushing etc. That won't happen in your example because you are not piping it anywhere. The `finish` event you are seeing is when everything has finished writing to the transform stream. You can see the other events by expanding your example:

```js
var through2 = require('through2')
var concat = require('concat-stream')

var stream = through2(function write (data, enc, cb) {
  cb(null, data)
}, function flush (cb) {
  console.log('flush')
  setTimeout(function () {
    console.log('still flushing')
    cb()
  }, 100)
})

var ws = concat(function (file) {
  console.log('file received by writestream')
})

ws.on('finish', function () {
  console.log('write stream finish event')
})

stream.on('finish', function () {
  console.log('transform finish event')
})

stream.on('end', function () {
  console.log('transform end event')
})

stream.pipe(ws)

stream.end('hello')
```

**Comment by noffle** [comment]
Thanks @mafintosh @gmaclennan for breaking this down for me.
